name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: RUSTFLAGS="--deny warnings" cargo build

  examples:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build & run examples
      run: RUSTFLAGS="--deny warnings" cargo run --examples

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4      
    - name: Run tests
      run: cargo test
