name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: build    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      run: RUSTFLAGS="--deny warnings" cargo build

  examples:
    name: examples
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4    
      run: RUSTFLAGS="--deny warnings" cargo build --examples

  test:
    name: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4          
      run: cargo test

  miri:
    name: miri
    runs-on: ubuntu-latest
    steps:    
    - uses: dtolnay/rust-toolchain@nightly 
    - uses: actions/checkout@v4      
      run: cargo +nightly miri test