name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: RUSTFLAGS="--deny warnings" cargo build

  examples:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Examples
      run: RUSTFLAGS="--deny warnings" cargo build --examples

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4      
    - name: Tests
      run: cargo test

  miri:
    runs-on: ubuntu-latest
    steps:
    - name: MIRI
    - uses: dtolnay/rust-toolchain@nightly 
    - uses: actions/checkout@v4      
      run: cargo +nightly miri test