name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: RUSTFLAGS="--deny warnings" cargo build

  examples:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4    
    - run: RUSTFLAGS="--deny warnings" cargo build --examples

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-careful      
    - uses: actions/checkout@v4
    - run: cargo careful test

  miri:
    runs-on: ubuntu-latest
    steps:    
    - uses: dtolnay/rust-toolchain@nightly
      with:
        toolchain: nightly
        components: miri      
    - uses: actions/checkout@v4      
    - run: cargo +nightly miri test