name: coverage

on: 
  workflow_dispatch:
  push:
    
jobs:
  coverage:
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin --verbose --all-features --workspace --out xml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          # token: ${{secrets.CODECOV_TOKEN}} # not required for public repos
          fail_ci_if_error: true    